version: '3.6'
services:
  face-recognition-app:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    network_mode: host
    devices:
      - '/dev/video0:/dev/video0'
    environment:
      - AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
      - AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
      - AWS_BUCKET_NAME="${AWS_BUCKET_NAME}"
  
